baseURL = "https://www.zulkiflizaki.my"
languageCode = "en-us"
title = "Ts. Zulkifli Zaki"
# theme = "avicenna"

# Your Google analytics code.
googleAnalytics = ""
timeout=3000
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Zulkifli Zaki {year}"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
  subtitle= "Educator | Professional Technologist"
  interests="Embedded Software and Real-Time Systems, Model-Based Development, Software Analysis and Design"
  cv_name= "resume-zulkiflizaki-2021.pdf"
  blog="/post/"
  home="/"

  # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
  featherIconsCDN = true

[[params.affilation]]
  name = "SEGi University and Colleges"
  position = "Educator and Researcher"
  contact = "zulkiflizaki@segi.edu.my"

[[params.affilation]]
  name = "RWTH Aachen University"
  position = "PhD Associate Reseacher"
  contact = "zaki@embedded.rwth-aachen.de"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/zulkiflizaki"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/zulkiflizaki"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/zulkiflizaki/"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:zulkiflizaki@hotmail.com"

[[params.introduction.paragraph]]
  text="""
  Completing PhD at Lehrstuhl Informatik 11 - Embedded Software of RWTH Aachen University, Germany under the supervision of Prof. Dr. -Ing. Stefan Kowalewski.
   """
[[params.introduction.paragraph]]
  text="""
  Previously, I received M.Sc. in Computer Science from University Teknologi Malaysia, Johor Bahru, Malaysia. My research focus on software analysis and design, specifically model-based development. I applied model-based analysis and design on the development of embedded software and real-time systems under the supervision of Associate Prof. Dr. Dayang Norhayati Abang Jawawi.
  """

[[params.projects]]
	[[params.projects.project]]
		name = "3D Model Reconstructor for Mobile Device"
		description  = "TBD"
		project_page = ""
		code_link = ""
		blog_link = ""

[[params.projects]]
	[[params.projects.project]]
		name = "Automated Traceability Recovery Method for Model-Based Software Artefacts"
		description  = "A research tool to facilitate trace links recovery for model-based software artefacts of embedded software."
		project_page = ""
		code_link = ""
		blog_link = ""

[[params.publications]]
  year="2022"

  [[params.publications.paper]]
		name = "Dynamic mobile anchor path planning for underwater wireless sensor networks"
		authors = "Mohammad Hafiz Mohamed, Kamalrulnizam Abu Bakar, Ismail Fauzi Isnin, __M Zulkifli M Zaki__, Herman, Fatima Tul Zuhra"
		dest  = "TELKOMNIKA Telecommunication, Computing, Electronics and Control"
		link = "http://telkomnika.uad.ac.id/index.php/TELKOMNIKA/article/view/19016"
		code_link = ""
		blog_link = ""

[[params.publications]]
  year="Preprint"

  [[params.publications.paper]]
    name = "Agent-based Techniques for Requirements Tracing"
    authors = "Karsten Jungnitsch, __Mohd Zulkifli Mohd Zaki__"
    dest  = "2018 Winter Seminar of Embedded Software"
    link = "https://embedded.rwth-aachen.com"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
    name = "Adaptation of Physical-Based Frameworks for Information Retrieval Improvement"
    authors = "Maximilian Conze, __Mohd Zulkifli Mohd Zaki__"
    dest  = "2018 Winter Seminar of Embedded Software"
    link = "https://embedded.rwth-aachen.com"
    code_link = ""
    blog_link = ""


[[params.publications]]
  year="2016"

  [[params.publications.paper]]
		name = "Integrated MARTE-based Model for Designing Component-Based Embedded Real-Time Software"
		authors = "__Mohd Z.M. Zaki__, Dayang N.A. Jawawi and Mohd Adham Isa"
		dest  = "International Journal of Software Engineering and Its Application"
		link = "https://www.semanticscholar.org/paper/Integrated-MARTE-based-Model-for-Designing-Embedded-Zaki-Jawawi/78b9b6118af1dcb20e0f9a14de8c4edc0c47a3a9"
		code_link = ""
		blog_link = ""
